import { QUOTES } from "./quotes";

export type TransitionTheme = {
  id: string;
  quote?: string;
  subtitle?: string;
  blur: number;
  opacity: number;
  duration: number;
  pin: number;
  alignment: "left" | "center" | "right";
  quoteSize: "small" | "medium" | "large" | "massive";
  mode: "Thought" | "Reflection" | "Manifesto" | "Silence";
};

export const transitionThemes: TransitionTheme[] = [
  {
    id: "hero",
    quote: QUOTES.heroExit.title,
    subtitle: QUOTES.heroExit.subtitle,
    blur: 50,
    opacity: 0.3,
    duration: 1.2,
    pin: 160,
    alignment: "center",
    quoteSize: "large",
    mode: "Thought",
  },
  {
    id: "age-of-intelligence",
    quote: QUOTES.ageExit.title,
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 120,
    alignment: "center",
    quoteSize: "medium",
    mode: "Thought",
  },
  {
    id: "problem",
    quote: QUOTES.problemExit.title,
    subtitle: QUOTES.problemExit.subtitle,
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 80,
    alignment: "left",
    quoteSize: "small",
    mode: "Thought",
  },
  {
    id: "vision",
    quote: QUOTES.visionExit.title,
    blur: 30,
    opacity: 0.2,
    duration: 1.2,
    pin: 160,
    alignment: "center",
    quoteSize: "massive",
    mode: "Reflection",
  },
  {
    id: "what-is-aegis",
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "medium",
    mode: "Reflection",
  },
  {
    id: "architecture",
    quote: QUOTES.architectureExit.title,
    blur: 30,
    opacity: 0.2,
    duration: 1.2,
    pin: 160,
    alignment: "right",
    quoteSize: "massive",
    mode: "Thought",
  },
  {
    id: "agent-ecosystem",
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "medium",
    mode: "Thought",
  },
  {
    id: "sectors",
    quote: QUOTES.sectorsExit.title,
    blur: 30,
    opacity: 0.2,
    duration: 1.2,
    pin: 120,
    alignment: "center",
    quoteSize: "medium",
    mode: "Thought",
  },
  {
    id: "technology",
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "medium",
    mode: "Reflection",
  },
  {
    id: "economics",
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "medium",
    mode: "Reflection",
  },
  {
    id: "roadmap",
    blur: 30,
    opacity: 0.2,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "medium",
    mode: "Reflection",
  },
  {
    id: "research",
    quote: QUOTES.researchExit.title,
    blur: 30,
    opacity: 0.2,
    duration: 1.2,
    pin: 160,
    alignment: "center",
    quoteSize: "large",
    mode: "Reflection",
  },
  {
    id: "join",
    blur: 30,
    opacity: 0.25,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "medium",
    mode: "Reflection",
  },
  {
    id: "manifesto",
    blur: 10,
    opacity: 0.1,
    duration: 1.5,
    pin: 100,
    alignment: "center",
    quoteSize: "large",
    mode: "Manifesto",
  },
  {
    id: "ending",
    blur: 0,
    opacity: 0.0,
    duration: 1.0,
    pin: 0,
    alignment: "center",
    quoteSize: "small",
    mode: "Silence",
  },
];
